version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: kjfdsjfhkdfkjdfhfksjdfhdsiu
      DEV_MYSQL_HOST: CSC535_project_db_1
      DEV_MYSQL_USER: csc535
      DEV_MYSQL_PASSWORD: welcome123
      DEV_MYSQL_DB: csc535
      DEV_MYSQL_CURSORCLASS: DictCursor
      LOGLEVEL: DEBUG
      FLASK_DEBUG: 1


  db:
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
