version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8000:5000"

  db:
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
