version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8000:5000"
    environment:
      FLASK_ENV: testing
      SECRET_KEY: kjfdsjfhkdfkjdfhfksjdfhdsiu
      TEST_MYSQL_HOST: CSC535_project_db_1
      TEST_MYSQL_USER: csc535
      TEST_MYSQL_PASSWORD: welcome123
      TEST_MYSQL_DB: csc535
      TEST_MYSQL_CURSORCLASS: DictCursor
      LOGLEVEL: INFO


  db:
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
