version: "2"

networks:
  micro_network:
    external:
      name: micro_network

services:
  app:
    container_name: user-service
    build: ./app
    links:
      - db
    ports:
      - "8001:5000"
    networks:
      - micro_network
    restart: always

  db:
    container_name: user_dbase
    platform: linux/x86_64
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - micro_network
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
